---

- hosts: all
  become: true # runs with sudo
  tasks:

  - name: install apache2 package
    apt:
      name: apache2

  - name: Start and enable Apache2
    service:
      name: apache2
      state: started
      enabled: true